### ISSUE TITLE
Track cycles in graphs

### ISSUE THREAD

**Issue by samm82** [samm82/TestingTesting#72]
If the "child-parent" relation is just that, it doesn't really make sense for there to be cycles in our graphs. At the very least, it would be beneficial to see what these cycles are and if they reveal a misunderstanding about any approaches involved!

# TODO:
- [x] Track self-cycles - should be trivial
- [ ] Track 2-cycles (e.g., A → B and A ← B) - should also be fairly straightforward
   - If describing as an item for Future Work, the potential cycle between QA and conformance testing could be used as an example
- [ ] Track longer cycles - will likely require a dot analysis tool, which might be too ambitious for me to automate
